# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerModule
  in_features: 528
  mlp_features: [384]
  num_heads: 8
  dim_feedforward: 2048
  dropout: 0.1
  activation: "relu"
  num_layers: 5

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
